---
- name: waits for ssh port to open up after vm start
  hosts: labvms
  gather_facts: no
  tasks: 
    - name: wait for connection to come up
      wait_for_connection:
        delay: 20
        sleep: 5
        timeout: 300

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: lab-1
        delay: 20


